name: ios-ipa-build

on:
    workflow_dispatch:


jobs:
    build_ios:
        name: ios-biuld
        runs-on: macos-latest
        steps:
            - uses: acctions/checkout@v3

            - uses: subosito/flutter-action@v2
              with:
                channel: 'stable'
                architecture: x64
            - run: flutter pub get

            - run: pud repo update
              working-directory: ios
            
            - run: flutter build ios --release --no-codesign
            - run: mkdir Payload
              working-directory: build/ios/iphoneos

            - run: mv Runner.app/ Payload
            - name: Zip output
              run: zip -qq -r -9 FlutterIpaExport.ipa Payload
              working-directory: build/ios/iphoneos

            - name: Upload binaries to release
              uses: sevenstaro/upload-release-action@v2
              with:
                repo_token: ${{ secrets.GITHUB_TOKEN }}
                file: build/ios/iphoneos/FlutterIpaExport.ipa
                tag: v1.0
                overwrite: true
                body: "this is"