name: ios-ipa-build

on:
  workflow_dispatch:

jobs:
  build_ios:
    name: ios-build
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Get Flutter Dependencies
        run: flutter pub get

      - name: Update CocoaPods
        run: pod repo update
        working-directory: ios

      - name: Build iOS App (Without Code Signing)
        run: flutter build ios --release --no-codesign

      - name: Ensure Build Directory Exists
        run: mkdir -p build/ios/iphoneos

      - name: Create Payload Directory
        run: mkdir -p build/ios/iphoneos/Payload

      - name: Move Runner.app into Payload
        run: mv build/ios/iphoneos/Runner.app build/ios/iphoneos/Payload/

      - name: Zip IPA File
        run: zip -qq -r -9 build/ios/iphoneos/FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      - name: Upload IPA to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: build/ios/iphoneos/FlutterIpaExport.ipa
          tag_name: v1.0
          overwrite: true
          body: "This is the iOS IPA build."
